### ISSUE TITLE
3.0.3 Multiplayer Server - Player Crashing

### ISSUE THREAD

**Issue by unclekakarot** [Darkosto/SevTech-Ages#1049]
Been playing on a multiplayer server with friends and everything was all good, updated from 3.0.1 today and been crashing alot. Not sure how to read the crash log so was hoping someone here could help.

[28/3/2018 21:31:44 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[28/3/2018 21:31:44 PM] ---------------------------------------------------------------------------------------
[28/3/2018 21:31:44 PM] 
[28/3/2018 21:31:44 PM] -- Head --
[28/3/2018 21:31:44 PM] Thread: Client thread
[28/3/2018 21:31:44 PM] Stacktrace:
[28/3/2018 21:31:44 PM] 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
[28/3/2018 21:31:44 PM] 	at betterwithmods.common.blocks.mechanical.tile.TileEntityWaterwheel.getRenderBoundingBox(TileEntityWaterwheel.java:144)
[28/3/2018 21:31:44 PM] 	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:704)
[28/3/2018 21:31:44 PM] 	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1345)
[28/3/2018 21:31:44 PM] 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
[28/3/2018 21:31:44 PM] 
[28/3/2018 21:31:44 PM] -- Affected level --
[28/3/2018 21:31:44 PM] Details:
[28/3/2018 21:31:44 PM] 	Level name: MpServer
[28/3/2018 21:31:44 PM] 	All players: 1 total; [EntityPlayerSP['**MINECRAFTUSERNAME**'/103475, l='MpServer', x=-175.03, y=87.05, z=1221.39]]
[28/3/2018 21:31:44 PM] 	Chunk stats: MultiplayerChunkCache: 441, 441
[28/3/2018 21:31:44 PM] 	Level seed: 0
[28/3/2018 21:31:44 PM] 	Level generator: ID 06 - quark_realistic, ver 0. Features enabled: false
[28/3/2018 21:31:44 PM] 	Level generator options: 
[28/3/2018 21:31:44 PM] 	Level spawn location: World: (72,64,256), Chunk: (at 8,4,0 in 4,16; contains blocks 64,0,256 to 79,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[28/3/2018 21:31:44 PM] 	Level time: 4946410 game time, 7441593 day time
[28/3/2018 21:31:44 PM] 	Level dimension: 0
[28/3/2018 21:31:44 PM] 	Level storage version: 0x00000 - Unknown?
[28/3/2018 21:31:44 PM] 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[28/3/2018 21:31:44 PM] 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
[28/3/2018 21:31:44 PM] 	Forced entities: 66 total; [EntitySkeleton['Skeleton'/246786, l='MpServer', x=-110.52, y=35.00, z=1219.50], EntitySkeleton['Skeleton'/246785, l='MpServer', x=-113.50, y=33.00, z=1220.50], EntityShadowCreature['Shadow Creature'/247303, l='MpServer', x=-99.50, y=25.00, z=1202.50], EntityZombie['Zombie'/247302, l='MpServer', x=-97.50, y=25.00, z=1204.50], EntityShadowCreature['Shadow Creature'/247305, l='MpServer', x=-99.14, y=25.00, z=1205.30], EntityShadowCreature['Shadow Creature'/247304, l='MpServer', x=-94.74, y=25.00, z=1206.47], EntityDepthsGhoul['Depths Ghoul'/247055, l='MpServer', x=-95.21, y=26.00, z=1148.99], EntityAbyssalZombie['Abyssal Zombie'/246924, l='MpServer', x=-98.50, y=45.00, z=1175.50], EntityCreeper['Creeper'/248467, l='MpServer', x=-208.50, y=45.00, z=1286.50], EntitySheep['Sheep'/245906, l='MpServer', x=-133.78, y=85.00, z=1231.63], EntitySheep['Sheep'/246307, l='MpServer', x=-194.50, y=92.00, z=1253.78], EntitySheep['Sheep'/246563, l='MpServer', x=-218.36, y=91.00, z=1270.20], EntityItemLoot['item.item.feather'/246306, l='MpServer', x=-181.90, y=91.00, z=1258.79], EntityPig['Pig'/246562, l='MpServer', x=-202.71, y=91.00, z=1267.63], EntitySheep['Sheep'/246561, l='MpServer', x=-177.50, y=93.00, z=1278.25], EntityItemLoot['item.item.feather'/246305, l='MpServer', x=-179.93, y=91.00, z=1257.45], EntityChicken['Chicken'/246304, l='MpServer', x=-182.21, y=91.00, z=1258.47], EntitySheep['Sheep'/246311, l='MpServer', x=-154.26, y=87.00, z=1252.40], EntityZombie['Zombie'/247975, l='MpServer', x=-130.50, y=37.00, z=1179.50], EntityDepthsGhoul['Depths Ghoul'/247974, l='MpServer', x=-127.50, y=37.00, z=1180.50], EntitySheep['Sheep'/246310, l='MpServer', x=-214.33, y=92.00, z=1255.40], EntitySheep['Sheep'/246309, l='MpServer', x=-223.85, y=91.00, z=1258.89], EntitySheep['Sheep'/246308, l='MpServer', x=-202.49, y=92.00, z=1258.59], EntityZombie['Zombie'/247976, l='MpServer', x=-131.50, y=37.00, z=1176.50], EntitySpider['Spider'/248621, l='MpServer', x=-126.50, y=13.00, z=1184.50], EntityPlayerSP['**MINECRAFTUSERNAME**'/103475, l='MpServer', x=-175.03, y=87.05, z=1221.39], EntityVillager['Villager'/245559, l='MpServer', x=-141.30, y=86.00, z=1186.70], EntityVillager['Villager'/245563, l='MpServer', x=-150.15, y=86.00, z=1188.10], EntityVillager['Villager'/245562, l='MpServer', x=-143.05, y=86.00, z=1186.80], EntityVillager['Villager'/245561, l='MpServer', x=-143.71, y=86.00, z=1190.33], EntityVillager['Villager'/245560, l='MpServer', x=-141.30, y=86.00, z=1186.30], EntityPig['Pig'/247359, l='MpServer', x=-241.52, y=69.00, z=1160.25], EntityVillager['Villager'/245566, l='MpServer', x=-142.81, y=86.00, z=1191.70], EntityPig['Pig'/247358, l='MpServer', x=-249.50, y=131.00, z=1186.68], EntityVillager['Villager'/245565, l='MpServer', x=-143.07, y=86.00, z=1190.96], EntityPig['Pig'/247357, l='MpServer', x=-247.24, y=132.00, z=1185.61], EntityVillager['Villager'/245564, l='MpServer', x=-142.30, y=86.00, z=1191.09], EntitySheep['Sheep'/245825, l='MpServer', x=-175.24, y=88.00, z=1154.45], EntityPig['Pig'/247360, l='MpServer', x=-252.16, y=122.00, z=1153.35], EntitySheep['Sheep'/247367, l='MpServer', x=-239.76, y=91.00, z=1278.79], EntityPig['Pig'/246347, l='MpServer', x=-227.68, y=133.00, z=1193.27], EntityPig['Pig'/246346, l='MpServer', x=-234.25, y=65.00, z=1165.49], EntityMagmaMonster['Magma Monster'/248521, l='MpServer', x=-208.50, y=50.00, z=1173.50], EntitySheep['Sheep'/247368, l='MpServer', x=-251.79, y=90.00, z=1276.51], EntityHorse['Horse'/200653, l='MpServer', x=-175.03, y=86.20, z=1221.39], EntityPig['Pig'/246348, l='MpServer', x=-227.71, y=90.00, z=1263.43], EntitySheep['Sheep'/246101, l='MpServer', x=-198.82, y=91.00, z=1243.26], EntityVillager['Villager'/245727, l='MpServer', x=-150.70, y=86.00, z=1191.70], EntityVillager['Villager'/245726, l='MpServer', x=-150.70, y=86.00, z=1187.30], EntitySheep['Sheep'/245982, l='MpServer', x=-187.69, y=87.00, z=1149.74], EntityVillager['Villager'/245731, l='MpServer', x=-144.20, y=86.00, z=1186.18], EntityChicken['Chicken'/247011, l='MpServer', x=-185.41, y=93.00, z=1296.88], EntityVillager['Villager'/245730, l='MpServer', x=-149.93, y=86.00, z=1187.30], EntityChicken['Chicken'/245729, l='MpServer', x=-158.47, y=86.00, z=1192.79], EntityZombie['Zombie'/248289, l='MpServer', x=-205.50, y=45.00, z=1288.50], EntityItemLoot['item.item.feather'/245728, l='MpServer', x=-157.76, y=86.00, z=1196.86], EntitySheep['Sheep'/246887, l='MpServer', x=-195.42, y=93.00, z=1294.80], EntitySheep['Sheep'/246886, l='MpServer', x=-123.71, y=91.00, z=1286.50], EntitySheep['Sheep'/245733, l='MpServer', x=-154.78, y=87.00, z=1172.50], EntityVillager['Villager'/245732, l='MpServer', x=-145.86, y=86.00, z=1191.70], EntityChicken['Chicken'/246889, l='MpServer', x=-228.51, y=93.00, z=1293.14], EntitySheep['Sheep'/246888, l='MpServer', x=-198.90, y=92.00, z=1283.61], EntitySheep['Sheep'/246894, l='MpServer', x=-166.55, y=95.00, z=1291.32], EntityChicken['Chicken'/245741, l='MpServer', x=-115.85, y=87.00, z=1212.50], EntityZombie['Zombie'/248301, l='MpServer', x=-237.50, y=60.00, z=1167.50], EntityFishSalmon['Salmon'/248178, l='MpServer', x=-204.24, y=60.20, z=1182.70]]
[28/3/2018 21:31:44 PM] 	Retry entities: 0 total; []
[28/3/2018 21:31:44 PM] 	Server brand: fml,forge
[28/3/2018 21:31:44 PM] 	Server type: Non-integrated multiplayer server
[28/3/2018 21:31:44 PM] Stacktrace:
[28/3/2018 21:31:44 PM] 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
[28/3/2018 21:31:44 PM] 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
[28/3/2018 21:31:44 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
[28/3/2018 21:31:44 PM] 	at net.minecraft.client.main.Main.main(SourceFile:123)
[28/3/2018 21:31:44 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[28/3/2018 21:31:44 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[28/3/2018 21:31:44 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[28/3/2018 21:31:44 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[28/3/2018 21:31:44 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[28/3/2018 21:31:44 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[28/3/2018 21:31:44 PM] 
[28/3/2018 21:31:44 PM] -- System Details --
[28/3/2018 21:31:44 PM] Details:
[28/3/2018 21:31:44 PM] 	Minecraft Version: 1.12.2
[28/3/2018 21:31:44 PM] 	Operating System: Windows 10 (amd64) version 10.0
[28/3/2018 21:31:44 PM] 	Java Version: 1.8.0_161, Oracle Corporation
[28/3/2018 21:31:44 PM] 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[28/3/2018 21:31:44 PM] 	Memory: 1334664944 bytes (1272 MB) / 4225236992 bytes (4029 MB) up to 4225236992 bytes (4029 MB)
[28/3/2018 21:31:44 PM] 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -Xms256M -Xmx4096M -XX:MetaspaceSize=256M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
[28/3/2018 21:31:44 PM] 	IntCache: cache: 0, tcache: 0, allocated: 10, tallocated: 101
[28/3/2018 21:31:44 PM] 	FML: MCP 9.42 Powered by Forge 14.23.2.2635 250 mods loaded, 250 mods active
[28/3/2018 21:31:44 PM] 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
[28/3/2018 21:31:44 PM] 
[28/3/2018 21:31:44 PM] 	| State  | ID                       | Version                      | Source                                            | Signature                                |
[28/3/2018 21:31:44 PM] 	|:------ |:------------------------ |:---------------------------- |:------------------------------------------------- |:---------------------------------------- |
[28/3/2018 21:31:44 PM] 	| UCHIJA | minecraft                | 1.12.2                       | minecraft.jar                                     | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | mcp                      | 9.42                         | minecraft.jar                                     | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | FML                      | 8.0.99.99                    | forge-1.12.2-14.23.2.2635-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
[28/3/2018 21:31:44 PM] 	| UCHIJA | forge                    | 14.23.2.2635                 | forge-1.12.2-14.23.2.2635-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
[28/3/2018 21:31:44 PM] 	| UCHIJA | ivtoolkit                | 1.3.3-1.12                   | minecraft.jar                                     | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | micdoodlecore            |                              | minecraft.jar                                     | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | norecipebook             | 1.1.0                        | minecraft.jar                                     | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | smoothfontcore           | 1.12.2-1.12                  | minecraft.jar                                     | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | bnbgamingcore            | 0.5.4                        | minecraft.jar                                     | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | foamfixcore              | 7.7.4                        | minecraft.jar                                     | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | smoothfont               | 1.12.2-1.13                  | SmoothFont-1.12.2-1.13.jar                        | None                                     |
[28/3/2018 21:31:44 PM] 	| UCHIJA | movillages               | 1.5.4                        | [1.12]MoVillages-1.5.4.jar                        | None                                     |
[28/3/2018 21:31:44 PM] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# **USERSDIR**\Instances\SevTechAges\crash-reports\crash-2018-03-28_21.31.44-client.txt
[28/3/2018 21:31:45 PM] AL lib: (EE) alc_cleanup: 1 device not closed
[28/3/2018 21:31:45 PM] Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[28/3/2018 21:31:45 PM] Checking for updated files!
[28/3/2018 21:31:49 PM] No updates found!

**Comment by ArbitraryHubris** [comment]
I have a related crashlog from a player - also references Better with Mods rendering:
https://pastebin.com/Rb9JG99r

**Comment by icha-senpai** [comment]
Same https://pastebin.com/V1tAZ7iU

**Comment by ChunkierDrew** [comment]
Also experiencing several crashes throughout today since advancing to Age 2. Friend of mine also had some issues, unfortunately i do not have his crash log. Hope this helps find the issue.  On a private server. Running 3.0.3, updated from 3.0.1 yesterday. https://pastebin.com/QdP9NyDi

**Comment by unclekakarot** [comment]
Not sure if it was the problem but removing the one water wheel I had seems to have stopped everyone on the server from crashing, Might of been a render bug with the water wheel, sucks but oh well.

**Comment by iDarper** [comment]
Updating better with mods will fix this issue

**Comment by artdude543** [comment]
Updating the mod will fix the issue and it will be fully fixed in the next version.
