### ISSUE TITLE
Game crashes when starting

### ISSUE THREAD

**Issue by Aqanico** [Darkosto/SevTech-Ages#1134]
When I start the game in Minecraft launcher it crashes directly

An unexpected problem has occurred and the game has crashed. We apologize for the inconvenience.

thats what it says

**Comment by justinrusso** [comment]
Please provide your crash log.

Go to your Sevtech folder > minecraft > crash-reports

**Comment by Aqanico** [comment]
I dont have the crash log folder because the game doesnt even starts

**Comment by artdude543** [comment]
The game will always create a logs folder. It's the first thing it does before executing the launch code. Otherwise, you'll need to tell the game to keep the console open and then pastebin the outputted logs (which do get logged to file also) before we can even attempt to help you.

You can't expect us to help you without logs/or details about the crash.

**Comment by Aqanico** [comment]
[20:50:19] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:50:19] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[20:50:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[20:50:19] [main/INFO]: Forge Mod Loader version 14.23.2.2635 for Minecraft 1.12.2 loading
[20:50:19] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 7:amd64:6.1, installed at C:\Users\Nico\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.1.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.8.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/INFO]: [AstralCore] Initialized.
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in BetterFoliage-MC1.12-2.1.10.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod mods.betterfoliage.loader.BetterFoliageLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod BetterFoliageLoader (mods.betterfoliage.loader.BetterFoliageLoader) is not signed!
[20:50:19] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[20:50:19] [main/WARN]: The coremod com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/INFO]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12-0.2.3.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Farseek-1.12-2.2.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod farseek.core.FarseekCoreMod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod FarseekCoreMod (farseek.core.FarseekCoreMod) is not signed!
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.9.5-1.12.2-anarchy.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.6.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[20:50:19] [main/WARN]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.64-dev.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[20:50:19] [main/WARN]: The coremod micdoodle8.mods.miccore.MicdoodlePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod MicdoodlePlugin (micdoodle8.mods.miccore.MicdoodlePlugin) is not signed!
[20:50:19] [main/WARN]: The coremod LoadingPlugin (com.LoadingPlugin) is not signed!
[20:50:19] [main/ERROR]: The coremod api.player.forge.PlayerAPIPlugin is requesting minecraft version 1.12.1 and minecraft is 1.12.2. It will be ignored.
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.4-122.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in SmoothFont-1.12.2-1.13.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[20:50:19] [main/WARN]: The coremod bre.smoothfont.asm.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[20:50:19] [main/WARN]: The coremod CorePlugin (bre.smoothfont.asm.CorePlugin) is not signed!
[20:50:19] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:50:19] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[20:50:19] [main/INFO]: Loading tweak class name codechicken.asm.internal.Tweaker
[20:50:19] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[20:50:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:50:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[20:50:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[20:50:20] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[20:50:20] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:170) ~[forge-1.12.2-14.23.2.2635.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:113) ~[forge-1.12.2-14.23.2.2635.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:76) ~[forge-1.12.2-14.23.2.2635.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.2.2635.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.2.2635.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.2.2635.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.2.2635.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165) ~[forge-1.12.2-14.23.2.2635.jar:?]
	... 2 more
[20:50:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[20:50:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[20:50:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[20:50:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[20:50:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[20:50:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[20:50:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Aqanico** [comment]
I solved the problem by myself. I deleted the modpack than deleted the versions folder and installed the pack again
