### ISSUE TITLE
Crash when eating cooked patty

### ISSUE THREAD

**Issue by Skullywag** [Darkosto/SevTech-Ages#1704]
## Issue / Bug
if you eat a cooked patty in 3.0.4 youll crash with:

java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.util.FoodStats.func_151686_a(SourceFile:32) ~[afp.class:?]
	at micdoodle8.mods.galacticraft.core.items.ItemFood.func_77654_b(ItemFood.java:162) ~[ItemFood.class:?]
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
	at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2778) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70103_a(EntityPlayer.java:421) ~[aed.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.func_70103_a(EntityPlayerSP.java:570) ~[bud.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147236_a(NetHandlerPlayClient.java:1026) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketEntityStatus.func_148833_a(SourceFile:38) ~[iz.class:?]
	at net.minecraft.network.play.server.SPacketEntityStatus.func_148833_a(SourceFile:11) ~[iz.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

## Expected Behavior
Not to crash

## Steps to Reproduce (for bugs)
1. Eat a patty
2. Crash

## Client Information
* Modpack Version: 3.0.4
* Java Version: 8
* Launcher Used: ATL
* Memory Allocated: 8Gb
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

## Server Information
* Java Version: 8
* Operating System: Windows 10
* Hoster/Hosting Soultion: Custom
* Sponge (Non-Vanilla Forge) Server?: nope

**Comment by justinrusso** [comment]
Please be sure you are updated. As well, see the following issue related to yours:

https://github.com/Darkosto/SevTech-Ages/issues/1656
