### ISSUE TITLE
Filtered hopper crashes server when using carry on to place it next to a fence post when full of soul sand

### ISSUE THREAD

**Issue by Skullywag** [Darkosto/SevTech-Ages#1706]
## Issue / Bug
As per title when placing a filtered hopper via carry on next to a fencepost and having it contain a stack of soul sand itll crash the server with:

net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to betterwithmods.common.blocks.mechanical.BlockMechMachines
	at betterwithmods.common.blocks.mechanical.tile.TileEntityFilteredHopper.getBlock(TileEntityFilteredHopper.java:400) ~[TileEntityFilteredHopper.class:?]
	at betterwithmods.common.blocks.mechanical.tile.TileEntityFilteredHopper.func_73660_a(TileEntityFilteredHopper.java:175) ~[TileEntityFilteredHopper.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1832) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more

## Expected Behavior
Not to crash

## Possible Solution
Something very similar to this was reportedly fixed in: 

https://github.com/Darkosto/SevTech-Ages/issues/1154

## Steps to Reproduce (for bugs)
1. place a filtered hopper
2. fill it with soul sand
3. pick it up via carry on
4. place the hopper down, no crash
5 place it next to a fencepost
6. crash. (if it doesnt crash I had a BWM cauldron on the diagonal.)

## Client Information
* Modpack Version: 3.0.4
* Java Version: 8
* Launcher Used: ATL
* Memory Allocated: 8Gb
* Server/LAN/Single Player: server
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version: 8
* Operating System: Windows 10
* Hoster/Hosting Soultion: custom
* Sponge (Non-Vanilla Forge) Server?: no

**Comment by artdude543** [comment]
It was supposed to be fixed in .4 but we pushed an update shortly after to fix more issues. Regardless the issue was fixed yours on an old version which we won't offer support unless it's reproducible in the latest version.
You'll be stuck in terms of progression on that version anyway unless your willing to run the commands to manually progress but .6 is pretty stable at the moment (nothing major is breaking progression)

But you do as you choose I can only recommend things. But don't expect support for an older version.
