### ISSUE TITLE
Crashing on world load

### ISSUE THREAD

**Issue by Borrii** [Darkosto/SevTech-Ages#1886]
## Expected Behavior
world loads

## Possible Solution
??

## Steps to Reproduce (for bugs)

1. load world
2. start new world

## Context
everytIme i load my world ofr start a new world, when loading flocks to 0% it crashes

## Logs

[crash-2018-04-16_18.36.35-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1914492/crash-2018-04-16_18.36.35-server.txt)

## Client Information

* Modpack Version:
* Java Version: 1.8.0.161 64x
* Launcher Used: twitch app

* Memory Allocated: 5120mb

* Server/LAN/Single Player: Single player
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by Ryex** [comment]
crash log lists
```
java.lang.UnsupportedOperationException
	at com.sun.nio.zipfs.ZipFileSystemProvider.ensureFile(ZipFileSystemProvider.java:96)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:110)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at net.minecraft.advancements.AdvancementManager.func_192777_a(AdvancementManager.java:161)
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:68)
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:156)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:122)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)
```
while I'm unfamilure with the component in question this type of error is tiplicaly related to file sytem permissions which usualy are not a problem on windows. Out of curiosity are you launching  from the Twitch client, ATLauncher, or somthing else?
