### ISSUE TITLE
Uhm Crab ?

### ISSUE THREAD

**Issue by xXNiugaXx** [Darkosto/SevTech-Ages#1974]
I dont Know <.<

Server Crash after Joining (Crash after Sync)

// I let you down. Sorry :(
 
Time: 4/7/18 10:30 AM
Description: Ticking entity
 
java.lang.NullPointerException: Ticking entity
    at net.minecraft.entity.ai.EntityLookHelper.func_75651_a(SourceFile:19)
    at thebetweenlands.common.entity.ai.EntityAIAttackOnCollide.func_75246_d(EntityAIAttackOnCollide.java:51)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
    at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(EntityMob.java:45)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(EntityMob.java:50)
    at thebetweenlands.common.entity.mobs.EntitySiltCrab.func_70071_h_(EntitySiltCrab.java:82)
    at net.minecraft.world.World.func_72866_a(World.java:1990)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
    at net.minecraft.world.World.func_72870_g(World.java:1952)
    at net.minecraft.world.World.func_72939_s(World.java:1756)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Thread.java:748)

all i see is "Game crash cuz a Crab ?" xD Help me 😆

**Comment by artdude543** [comment]
Thank you for reporting an issue! But as stated in the issue template _(which you have ignored and deleted)_ any issues which don't follow the format will be closed and ignored.

We created the issue template to help us help you! In meaning that it asks for all the information we need to help you with the bug/crash/issue etc.. Without that critial information we can't help you. So if you would like to report the issue again please re-create a issue using the provided template.

Thanks again for reporting, and we hope you enjoy the pack!
