### ISSUE TITLE
Crash Loop while using Blood Magic's Sigil of the fast miner inside a sigil of holding

### ISSUE THREAD

**Issue by Crobitaille** [Darkosto/SevTech-Ages#2233]
## Issue / Bug
activated a sigil of the fast miner that was stored in a sigil of holding
Crashed and now I can't play my world.

## Expected Behavior
Shouldn't Crash

## Steps to Reproduce (for bugs)
Activate a sigil of the faster miner that's stored inside a sigil of holding

## Context
Just turned it on and walked a step then the game crashed.

## Logs
Time: 5/5/18 5:32 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
    at WayofTime.bloodmagic.util.helper.NetworkHelper.getSoulNetwork(NetworkHelper.java:63)
    at WayofTime.bloodmagic.item.ItemSigilToggleable.func_77663_a(ItemSigilToggleable.java:84)
    at WayofTime.bloodmagic.item.sigil.ItemSigilHolding.tickInternalInventory(ItemSigilHolding.java:164)
    at WayofTime.bloodmagic.item.sigil.ItemSigilHolding.func_77663_a(ItemSigilHolding.java:151)
    at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
    at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
    at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Thread.java:745)

## Client Information

* Modpack Version: 3.0.6
* Java Version: Version 8 Update 161 (build 1.8.0_161-b12)
* Launcher Used:
Curse Launcher
* Memory Allocated: 12288MB RAM

Related Issue: 
https://github.com/Darkosto/SevTech-Ages/issues/2153

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/2153

**Comment by artdude543** [comment]
This is already fixed for 3.0.7 stop making a new issue as you already searched the tracker.... >.>
