### ISSUE TITLE
Ferdinand's Flowers calls client side code on server.

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#41]
Note: I couldn't find this mod on Curse, or find any info on it via google. 

MC: 1.12.1
Version: 1.7
Jar: Ferdinand's Flowers-1.7-1.12.jar

```java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at c0_0ry.ferdinandsflowers.worldgen.WorldGenCffFlowers2.generate(WorldGenCffFlowers2.java:72)
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Darkosto** [comment]
Just got the fix from C0_ry.
