### ISSUE TITLE
FiniteWaterControl calls client code on the server. 

### ISSUE THREAD

**Issue by darkhax** [Darkosto/SevTech-Ages#42]
MC: 1.12.1
Version: 1.0

Note: I couldn't find a dedicated issue tracker for this mod. 

```
java.lang.NoSuchMethodError: net.minecraft.world.biome.Biome.func_185359_l()Ljava/lang/String;
	at flaxbeard.fwc.FiniteWaterControl.handleFiniteFluids(FiniteWaterControl.java:84)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1105_FiniteWaterControl_handleFiniteFluids_CreateFluidSourceEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.canCreateFluidSource(ForgeEventFactory.java:661)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:70)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:738)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Darkosto** [comment]
Mod has been replaced and the replacement works on servers.
