### ISSUE TITLE
Game not Starting.( log attached)

### ISSUE THREAD

**Issue by dottzpg** [Darkosto/SevTech-Ages#810]
The log:

[15:46:25] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:46:25] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1845367/latest.log)

**Comment by artdude543** [comment]
Try reinstalling the pack. As Forge is somehow missing in your install. What launcher are you using also?

**Comment by dottzpg** [comment]
@artdude543 
https://imgur.com/a/ZVBlD
I deleted and reinstaled everything.
Do you recomand to delete everything?

**Comment by artdude543** [comment]
Okay try this; when you're on the pack on the Twitch Launcher top right you'll see a button with the text `..` (next to `Get More Content`) click that and then `Repair Minecraft` and then try again. If not try a re-install of the pack.

**Comment by dottzpg** [comment]
@artdude543 Thank you, is working now, loading properly. This was a fix. Thanks again and sorry for disturbing.

**Comment by artdude543** [comment]
No worries happy to help anytime! Glad it's all fixed and happy dying (I mean playing)! Kappa 😉
