### ISSUE TITLE
Crash on world creation

### ISSUE THREAD

**Issue by Nickoladze** [Darkosto/SevTech-Ages#818]
[crash-2018-03-25_12.58.16-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1845557/crash-2018-03-25_12.58.16-client.txt)

Relevant bits:
`Description: Unexpected error
java.lang.ExceptionInInitializerError
	at hunternif.mc.atlas.client.gui.ExportProgressOverlay.draw(ExportProgressOverlay.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_775_ExportProgressOverlay_draw_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:904)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:206)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at sun.awt.shell.Win32ShellFolder2.getFileSystemPath(Win32ShellFolder2.java:571)
	at sun.awt.shell.Win32ShellFolder2.access$400(Win32ShellFolder2.java:72)
	at sun.awt.shell.Win32ShellFolder2$10.call(Win32ShellFolder2.java:756)
	at sun.awt.shell.Win32ShellFolder2$10.call(Win32ShellFolder2.java:747)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at sun.awt.shell.Win32ShellFolderManager2$ComInvoker$3.run(Win32ShellFolderManager2.java:511)
	at java.lang.Thread.run(Thread.java:745)`

JVM arguments:
`-Xmx8192m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\XXX\Documents\Curse\Minecraft\Instances\SevTech Ages" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US`

Installed via Twitch app. Fresh Minecraft instance with default settings (besides launch params) all the way down.
pack version 3.0.1
forge-14.23.2.2634

**Comment by Nickoladze** [comment]
Removing Antique Atlas fixes the crash

**Comment by justinrusso** [comment]
Removing antique atlas will cause script issues

**Comment by artdude543** [comment]
I've not seen this crash since (well ages) can you see if you still get this issue @Nickoladze ?

**Comment by artdude543** [comment]
Closing due to no updates and we've had a lot of mod changes/updates since .1 so if you get the issue again on .4 please re-file the error :
