### ISSUE TITLE
Crash when making FireSticks

### ISSUE THREAD

**Issue by Norsered** [Darkosto/SevTech-Ages#894]
When making firesticks in player inventory, game crashed.
primal_tech.items.ItemFireSticks

[crash-2018-03-26_13.31.52-server.txt](https://github.com/Darkosto/SevTech-Ages/files/1849126/crash-2018-03-26_13.31.52-server.txt)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  BNBGamingCore (BNBGamingCore-1.12-0.5.4.jar)
  CorePlugin (SmoothFont-1.12.2-1.12-b1.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  FarseekCoreMod (Farseek-1.12-2.2.4.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LoadingPlugin (noRecipeBook_v1.1.0formc1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.4-core.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.164.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.1.10.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 3/26/18 1:31 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at primal_tech.items.ItemFireSticks.func_77663_a(ItemFireSticks.java:59)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:

**Comment by justinrusso** [comment]
https://github.com/Darkosto/SevTech-Ages/issues/869
